export const EVENT_BEAM_SELECTED = "EVENT_BEAM_SELECTED";
export const EVENT_BEAM_DESELECTED = "EVENT_BEAM_DESELECTED";
export const EVENT_GUI_PLACE_BEAM_CLICKED = "EVENT_GUI_PLACE_BEAM_CLICKED";
export const EVENT_GUI_SELECT_BEAM_CLICKED = "EVENT_GUI_SELECT_BEAM_CLICKED";
export const EVENT_GUI_CUT_BEAM_CLICKED = "EVENT_GUI_CUT_BEAM_CLICKED";