export const EVENT_BEAM_SELECTED = "EVENT_BEAM_SELECTED";
export const EVENT_BEAM_DESELECTED = "EVENT_BEAM_DESELECTED";
export const EVENT_GUI_INPUT_MODE_CHANGED = "EVENT_GUI_INPUT_MODE_CHANGED_(GuiInputMode)";